server:
  port: 8080

spring:
  application:
    name: lucky-letter
  profiles:
    active: local

  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console       # H2 Console 접속 주소

  datasource:
    url: ${url}
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: none                # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate: # hibernate property 설정
        format_sql: true              # 쿼리 로그 포맷 (정렬)
        show_sql: true                # 쿼리 로그 출력
